#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib

outdir = sys.argv[1]

testlib.validate(path="{}/00600cell/".format(outdir),
                 outdir=outdir,
                 start=[-6,-6,0],
                 end=[6,6,0],
                 vars=["Temp","disp_x","stress_xx"],
                 tolerance=0.01,
                 generate_ref_data = False)
exit(0)





