#!/usr/bin/env python3
"""Generate/run standalone planar LowMach comparisons with Chen (2002) Fig. 4."""
import argparse
import hashlib
import json
import math
import os
from pathlib import Path
import subprocess
import time

from scipy.optimize import brentq

STUDY = Path(__file__).resolve().parent
ROOT = STUDY.parent


def reference(parameters, t, q_cal):
    b, ap = parameters["binder"], parameters["AP"]
    w = ap["density_kg_m3"] * t / (ap["density_kg_m3"] * t + b["density_kg_m3"] * (1-t))
    values = {key: (1-w)*b[key] + w*ap[key] for key in
              ("density_kg_m3", "cp_J_kg_K", "heat_release_J_kg")}
    values["A_m_s"] = math.exp((1-t)*math.log(b["A_m_s"]) + t*math.log(ap["A_m_s"]))
    values["activation_temperature_K"] = (1-t)*b["activation_temperature_K"] + t*ap["activation_temperature_K"]
    x = ap["conductivity_W_m_K"] / b["conductivity_W_m_K"]
    a = (1-t)*(1-x)
    values["conductivity_W_m_K"] = b["conductivity_W_m_K"]*((a+math.sqrt(a*a+4*x))/2)**2
    q = q_cal * 41840.0

    def solve(material):
        rho, cp, Q = (material[k] for k in ("density_kg_m3", "cp_J_kg_K", "heat_release_J_kg"))
        A, E = material["A_m_s"], material["activation_temperature_K"]
        f = lambda T: rho*A*math.exp(-E/T)*(cp*(T-parameters["T0_K"])-Q)-q
        lo, hi = max(1.0, parameters["T0_K"]+Q/cp), 2000.0
        hi = max(hi, lo+1000)
        while f(hi) < 0:
            hi *= 2
        Ts = brentq(f, lo, hi, xtol=1e-10)
        return Ts, A*math.exp(-E/Ts)

    Ts, r = solve(values)
    _, rb = solve(b)
    _, rap = solve(ap)
    return {**values, "ap_volume_fraction": t, "ap_mass_fraction": w,
            "heat_flux_cal_cm2_s": q_cal, "heat_flux_W_m2": q,
            "surface_temperature_K": Ts, "regression_speed_m_s": r,
            "eq15_regression_speed_m_s": 1.0/((1-t)/rb+t/rap),
            "thermal_length_m": values["conductivity_W_m_K"]/(values["density_kg_m3"]*values["cp_J_kg_K"]*r)}


def generate(parameters, t, q, args):
    expected = reference(parameters, t, q)
    delta, speed, Ts = (expected[k] for k in ("thermal_length_m", "regression_speed_m_s", "surface_temperature_K"))
    width = args.width_ratio * delta
    dy = width / args.cells_per_width
    ny = int(math.ceil((args.relaxations+12)*delta/dy/8))*8
    lo_y = -(args.relaxations+8)*delta
    hi_y = lo_y + ny*dy
    end_time = args.relaxations*delta/speed
    plot_interval = end_time / 40
    pressure = args.pressure
    name = f"q{q:g}_t{t:.3f}_e{args.width_ratio:g}_n{args.cells_per_width}_p{pressure:g}{args.tag}"
    case = STUDY / "runs" / name
    case.mkdir(parents=True, exist_ok=True)
    b, ap = parameters["binder"], parameters["AP"]
    eta = f"(0.5-0.5*tanh(2.0*y/{width:.17g}))"
    # The fixed heating slab lies above the initially planar surface, entirely
    # in gas. Its integral is q; the insulated top leaves conduction downward.
    # The actual flux reaching the regressing surface must be measured, not assumed.
    source_lo, source_hi = hi_y-delta, hi_y
    temperature = f"({parameters['T0_K']:.17g}+({Ts:.17g}-{parameters['T0_K']:.17g})*exp(min(y,0.0)/{delta:.17g})+{expected['heat_flux_W_m2']/args.gas_conductivity:.17g}*(max(y,0.0)-max(y-{source_lo:.17g},0.0)^2/{2*delta:.17g}))"
    v0 = 1.5*width  # lambda=1, mobility=1, w0=0, w12=2, w1=1
    deck = f'''# Standalone prescribed-net-flux comparison. Generated by run_study.py.
# Reference solution initializes temperature and sizes the domain only.
# Heating uses the existing spatial-expression input, not modified source.
# Gas-side incident flux is independently checked in postprocessing.
plot_file = {case.relative_to(ROOT)}/output
amr.plot_int = -1
amr.plot_dt = {plot_interval:.17g}
amr.max_level = 0
amr.n_cell = {args.nx} {ny}
amr.max_grid_size = {ny}
amr.blocking_factor = 4
amr.regrid_int = -1
max_step = 200000
stop_time = {end_time:.17g}
timestep = {min(1e-7, 0.05*dy/speed):.17g}
dynamictimestep.on = 1
dynamictimestep.min = 1.0e-14
dynamictimestep.max = {0.2*dy/speed*args.dt_scale:.17g}
dynamictimestep.verbose = 0
geometry.prob_lo = 0.0 {lo_y:.17g} 0.0
geometry.prob_hi = {args.nx*dy:.17g} {hi_y:.17g} 0.0
geometry.is_periodic = 1 0 0
integration.type = RungeKutta
integration.rk.type = 3
system.amount = kmol
gas.mw = 26.0_g/mol
gas.thermo.type = cpconstant
gas.thermo.cpconstant.cp_moles = {0.026*args.gas_cp:.17g}_J/mol/K
gas.thermo.cpconstant.h0 = 0.0
gas.thermo.cpconstant.s0 = 0.0
gas.thermo.cpconstant.Tref = 300.0_K
gas.transport.type = rocfire
gas.transport.rocfire.lambda_a = 0.0
gas.transport.rocfire.lambda_b = {args.gas_conductivity:.17g}
gas.eos.type = tpg
species.names = product_gas HTPB_solid AP_solid
product_gas.mechanics = fluid
HTPB_solid.mechanics = rigid_solid
AP_solid.mechanics = rigid_solid
HTPB_solid.reference_density = {b['density_kg_m3']:.17g}
AP_solid.reference_density = {ap['density_kg_m3']:.17g}
HTPB_solid.specific_heat = {b['cp_J_kg_K']:.17g}
AP_solid.specific_heat = {ap['cp_J_kg_K']:.17g}
HTPB_solid.thermal_conductivity = {b['conductivity_W_m_K']:.17g}
AP_solid.thermal_conductivity = {ap['conductivity_W_m_K']:.17g}
chemistry.model.type = frozen
chemistry.solver.type = forward_euler
mechanisms.names = binder_regression
binder_regression.type = phase_change
binder_regression.phase_change.in = HTPB_solid
binder_regression.phase_change.out = product_gas
binder_regression.phase_change.rate_multiplier = {b['A_m_s']/v0:.17g}
binder_regression.phase_change.activation_temperature = {b['activation_temperature_K']:.17g}
binder_regression.phase_change.homogeneous = true
binder_regression.phase_change.homogeneous.ap_solid = AP_solid
binder_regression.phase_change.homogeneous.ap_gas = product_gas
binder_regression.phase_change.homogeneous.mass_fraction = {expected['ap_mass_fraction']:.17g}
binder_regression.phase_change.homogeneous.ap_rate_multiplier = {ap['A_m_s']/v0:.17g}
binder_regression.phase_change.homogeneous.ap_activation_temperature = {ap['activation_temperature_K']:.17g}
binder_regression.phase_change.homogeneous.binder_heat_release = {b['heat_release_J_kg']:.17g}
binder_regression.phase_change.homogeneous.ap_heat_release = {ap['heat_release_J_kg']:.17g}
binder_regression.phase_change.phase_field.type = allencahn
binder_regression.phase_change.phase_field.allencahn.mobility = 1.0
binder_regression.phase_change.phase_field.allencahn.lambda = 1.0
binder_regression.phase_change.phase_field.allencahn.kappa = {3*width*width:.17g}
binder_regression.phase_change.phase_field.allencahn.w0 = 0.0
binder_regression.phase_change.phase_field.allencahn.w12 = 2.0
binder_regression.phase_change.phase_field.allencahn.w1 = 1.0
rigid.relaxation_time = {args.rigid_relaxation:.17g}
rigid.velocity = 0.0 0.0
advection.type = muscl
advection.muscl.limiter.type = minmod
cfl = 0.4
phase_field.cfl = 0.75
include_viscosity = 0
include_conduction = 1
advect_temperature = {args.advect_temperature}
projection.enabled = 1
projection.tol_rel = 1.0e-8
projection.tol_abs = 1.0e-12
projection.verbose = 0
projection.update_pressure = 0
diffusion.tol_rel = 1.0e-10
diffusion.tol_abs = 1.0e-12
diffusion.verbose = 0
diagnostics.extended_fields = 1
diagnostics.interval = 0
heat_source.ic.type = expression
heat_source.ic.expression.unit = W/m^3
heat_source.ic.expression.region0 = "{expected['heat_flux_W_m2']/delta:.17g}*(y>{source_lo:.17g})"
HTPB_solid.density.ic.type = expression
HTPB_solid.density.ic.expression.region0 = "{expected['density_kg_m3']:.17g}*{eta}"
product_gas.density.ic.type = expression
product_gas.density.ic.expression.region0 = "(1.0-{eta})*{pressure:.17g}/(319.7870237751246*{temperature})"
velocity.ic.type = constant
velocity.ic.constant.value = 0.0 0.0
temperature.ic.type = expression
temperature.ic.expression.region0 = "{temperature}"
pressure.ic.type = constant
pressure.ic.constant.value = {pressure:.17g}
component_density.bc.type = constant
component_density.bc.constant.type.xlo = periodic
component_density.bc.constant.type.xhi = periodic
component_density.bc.constant.type.ylo = neumann
component_density.bc.constant.type.yhi = neumann
velocity.bc.type = constant
velocity.bc.constant.type.xlo = periodic
velocity.bc.constant.type.xhi = periodic
velocity.bc.constant.type.ylo = dirichlet
velocity.bc.constant.val.ylo = 0.0 0.0
velocity.bc.constant.type.yhi = neumann
temperature.bc.type = constant
temperature.bc.constant.type.xlo = periodic
temperature.bc.constant.type.xhi = periodic
temperature.bc.constant.type.ylo = dirichlet
temperature.bc.constant.val.ylo = {parameters['T0_K']:.17g}
temperature.bc.constant.type.yhi = neumann
pressure.bc.type = constant
pressure.bc.constant.type.xlo = periodic
pressure.bc.constant.type.xhi = periodic
pressure.bc.constant.type.ylo = neumann
pressure.bc.constant.type.yhi = dirichlet
pressure.bc.constant.val.yhi = {pressure:.17g}
'''
    if (case / "input").exists() and (case / "input").read_text() != deck:
        raise SystemExit(f"Input already exists with different settings: {case}. Use a new --tag.")
    (case / "input").write_text(deck)
    metadata = {"name": name, "reference": expected, "width_m": width, "dx_m": dy,
                "parameters": parameters,
                "width_ratio": args.width_ratio, "cells_per_width": args.cells_per_width,
                "pressure_Pa": pressure, "gas_conductivity_W_m_K": args.gas_conductivity,
                "gas_cp_J_kg_K": args.gas_cp, "T0_K": parameters['T0_K'],
                "gas_constant_J_kg_K": 319.7870237751246,
                "advect_temperature": bool(args.advect_temperature),
                "rigid_relaxation_time_s": args.rigid_relaxation,
                "source_y_m": [source_lo, source_hi], "heating": "fixed gas slab; input-only",
                "relaxations": args.relaxations, "duration_s": end_time,
                "domain_y_m": [lo_y, hi_y], "nx": args.nx, "ny": ny, "dt_scale": args.dt_scale,
                "input_sha256": hashlib.sha256(deck.encode()).hexdigest()}
    (case / "case.json").write_text(json.dumps(metadata, indent=2)+"\n")
    return case


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--parameters", type=Path, default=STUDY/"reference/parameters.json")
    p.add_argument("--fractions", type=float, nargs="+", default=[0, .2, .4, .6, .8, 1])
    p.add_argument("--fluxes", type=float, nargs="+", default=[200, 500, 1000])
    p.add_argument("--width-ratio", type=float, default=.25)
    p.add_argument("--cells-per-width", type=int, default=8)
    p.add_argument("--nx", type=int, default=32)
    p.add_argument("--pressure", type=float, default=1e8)
    p.add_argument("--gas-conductivity", type=float, default=100)
    p.add_argument("--gas-cp", type=float, default=1000)
    p.add_argument("--advect-temperature", type=int, choices=[0, 1], default=0)
    p.add_argument("--rigid-relaxation", type=float, default=1e-7)
    p.add_argument("--relaxations", type=float, default=6)
    p.add_argument("--dt-scale", type=float, default=1)
    p.add_argument("--tag", default="")
    p.add_argument("--run", action="store_true")
    p.add_argument("--timeout", type=float, default=900)
    args = p.parse_args()
    if args.gas_cp <= 319.7870237751246:
        p.error("The ideal-gas surrogate requires cp > R (319.787 J/kg/K).")
    parameters = json.loads(args.parameters.read_text())
    for q in args.fluxes:
        for t in args.fractions:
            case = generate(parameters, t, q, args)
            print(case.relative_to(ROOT), flush=True)
            if args.run:
                status_file = case/"run.json"
                if status_file.exists() and json.loads(status_file.read_text()).get("returncode") == 0:
                    print("Completed case retained", flush=True)
                    continue
                command = [str(ROOT/"bin/lowmach-2d-clang++"), str(case/"input")]
                start = time.monotonic()
                with (case/"stdout.log").open("w") as stream:
                    try:
                        result = subprocess.run(command, cwd=ROOT, stdout=stream, stderr=subprocess.STDOUT,
                                                timeout=args.timeout, check=False)
                        code = result.returncode
                    except subprocess.TimeoutExpired:
                        code = "timeout"
                status_file.write_text(json.dumps({"command": command, "returncode": code,
                    "elapsed_s": time.monotonic()-start,
                    "binary_sha256": hashlib.sha256((ROOT/"bin/lowmach-2d-clang++").read_bytes()).hexdigest(),
                    "input_sha256": hashlib.sha256((case/"input").read_bytes()).hexdigest()}, indent=2)+"\n")
                print(f"  returncode={code}, elapsed={time.monotonic()-start:.2f}s", flush=True)
                if code != 0:
                    raise SystemExit(f"Run failed; inspect {case/'stdout.log'}")


if __name__ == "__main__":
    main()
