#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import numpy, yt, pylab, os, pandas, sys, math

outdir = sys.argv[1]

generate_ref_data = False  # Change to True if you need to generate new reference data
tolerance = 0.01

testlib.validate(path="{}/00200cell/".format(outdir),
                 outdir=outdir,
                 start=[0,2.5,0],
                 end=[5.0,2.5,0],
                 vars=["Eta001","disp_x","stress_xx"],
                 tolerance=tolerance,
                 reference="reference/reference.csv")

exit(0)

