#!/usr/bin/env bash                                                                                                                                                              
#SBATCH --time=10:00                                                                                                                                                                
#SBATCH --nodes=1                                                                                                                                                                    
#SBATCH --ntasks-per-node=16
#SBATCH --mem-per-cpu=2000
#SBATCH --job-name="compile"
#SBATCH --output="%x-%j-compile-log.txt"
#SBATCH --mail-user=mungerct@iastate.edu
#SBATCH --mail-type=BEGIN
make clean
module purge
module load git
module load openmpi gcc eigen
./configure --get-eigen --dim=2
srun --nodes=1 --cpus-per-task=16 --mem-per-cpu=1G --time=10:00 make -j16
