#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import glob

outdir = sys.argv[1]
reference = sys.argv[2]

path = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 start=[0.0000,0.00007,0],
                 end=[0.0005,0.00007,0],
                 vars=["eta","stress_xx","stress_yy","pressure"],
                 tolerance=[0.05,0.05,0.05,0.05],
                 abs_tolerance=[0.05,0.01,0.01,0.01],
                 reference=reference,
                 generate_ref_data = True,
)
exit(0)