#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import glob

outdir = sys.argv[1]

tol = 1e-2

path = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 reference="reference/reference-2d.csv",
                 start=[2.5, 0],
                 end  =[2.5, 3.0],
                 coord = 'y',
                 vars=["momentumx","density","pressure"],
                 tolerance=[tol, tol, tol],
                 generate_ref_data = False,
                 tight_layout=False,
)

testlib.warning("WARNING: currently using fairly generous tolerances.")

exit(0)





