#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import glob

outdir = sys.argv[1]
reference = sys.argv[2]

tol = 1e-2

path = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 reference=reference,
                 start=[2.5, 0],
                 end  =[2.5, 3.0],
                 coord = 'y',
                 vars=["momentumx","momentumy","density","pressure"],
                 tolerance=[tol, tol, tol, tol],
                 abs_tolerance=1e8,
                 #generate_ref_data = True,
                 tight_layout=False,
)

exit(0)





