#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import glob

outdir = sys.argv[1]
reference = sys.argv[2]

path = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 start=[-8,-16,0],
                 end=[8,16,0],
                 vars=["Eta001","stress_xx"],
                 tolerance=[0.01,0.1],
                 abs_tolerance = 10000, 
                 reference=reference,
                 generate_ref_data = False,
)
exit(0)





