#!/usr/bin/env python3
import sys, glob
sys.path.insert(0,"../../scripts")
import testlib

outdir = sys.argv[1]
checkfile = sys.argv[2]
datfile = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

if "-x" in checkfile:
    start = [-3,0]
    end   = [4,0]
    vars = ["eta","etaDensity","Velocity001","Pressure"]
elif "-y" in checkfile:
    raise "Not implemented yet"


testlib.validate(path=datfile,
                 outdir=outdir,
                 start=start,
                 end=end,
                 vars=vars,
                 tolerance=1E-4,
                 generate_ref_data = False,
                 reference=checkfile)
exit(0)





