#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import glob

outdir = sys.argv[1]
reference = sys.argv[2]

path = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 reference=reference,
                 start=[0.0, 0.0],
                 end  =[0.0, 3.0],
                 coord = 'y',
                 vars=["momentum001"],
                 tolerance=[0.001],
                 generate_ref_data = False,
                 tight_layout=False,
)
exit(0)





