#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import glob

outdir = sys.argv[1]
reference = sys.argv[2]

tol = 0.055

path = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 reference="reference/eps0.20.dat",
                 start=[0.0, 0.0],
                 end  =[0.0, 3.0],
                 coord = 'y',
                 vars=["momentumx"],
                 tolerance=[tol],
                 generate_ref_data = False,
                 tight_layout=False,
)

exit(0)





