#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import glob

outdir = sys.argv[1]

tol = 1e-2

path = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 reference="reference/reference-2d.csv",
                 start=[-2, 0],
                 end  =[3, 4],
                 coord = "x",
                 vars=["momentumx","density","pressure","eta"],
                 tolerance=[tol, tol, tol, tol],
                 abs_tolerance=[tol, tol, tol, tol],
                 generate_ref_data = False,
                 tight_layout=False,
)

exit(0)





