version: 2
dependencies:
  - sudo  

jobs:
  2D:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - checkout
      - run:
          name: Installing preliminaries
          command: 'apt-get update && 
                    apt-get install -qq software-properties-common'
      - run:
          name: Updating compilers
          command: 'add-apt-repository -y ppa:ubuntu-toolchain-r/test &&
                    apt-get update -qq &&
                    apt-get install -qq g++-6  &&
                    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90 &&
                    apt-get install -y mpich libmpich-dev libmpich12 gfortran libeigen3-dev &&
                    export LIBRARY_PATH=${LIBRARY_PATH}:/usr/lib/gcc/x86_64-linux-gnu/4.8/'
      - run:
          name: Building Alamo
          command: 'bash ./.build.sh 2'
      - run:
          name: Running Unit Tests
          command: 'bash ./.test.sh 2'
  3D:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - checkout
      - run:
          name: Installing preliminaries
          command: 'apt-get update && 
                    apt-get install -qq software-properties-common'
      - run:
          name: Updating compilers
          command: 'add-apt-repository -y ppa:ubuntu-toolchain-r/test &&
                    apt-get update -qq &&
                    apt-get install -qq g++-6  &&
                    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90 &&
                    apt-get install -y mpich libmpich-dev libmpich12 gfortran libeigen3-dev &&
                    export LIBRARY_PATH=${LIBRARY_PATH}:/usr/lib/gcc/x86_64-linux-gnu/4.8/'
      - run:
          name: Building Alamo
          command: 'bash ./.build.sh 3'
      - run:
          name: Running Unit Tests
          command: 'bash ./.test.sh 3'

workflows:
  version: 2
  build:
    jobs:
      - "2D"
      - "3D"
