#!/usr/bin/env python3
import numpy, pylab, os, sys

outdir = sys.argv[1]
ref = sys.argv[2]

tolerance = 1E-4

def integrate(x,y):
    ret = 0
    for i in range(len(x)-1): ret = ret + 0.5*(y[i+1]+y[i]) * (x[i+1]-x[i])
    return ret




ref  = numpy.loadtxt(ref.format(outdir),skiprows=1)
data = numpy.loadtxt("{}/thermo.dat".format(outdir),skiprows=1)


sig_diff = numpy.interp(data[:,0], ref[:,0], ref[:,2]) - data[:,2]
sig_norm = numpy.sqrt(integrate(ref[:,0],ref[:,2]*ref[:,2]))

error = numpy.sqrt(integrate(data[:,0],sig_diff**2)) / sig_norm


pylab.clf()
pylab.plot(ref[:,0],ref[:,2],marker='o',label="reference")
pylab.plot(data[:,0],data[:,2],label="test")
pylab.legend()
pylab.xlabel("time")
pylab.ylabel("stress")
pylab.savefig("{}/stress_time.png".format(outdir))

pylab.clf()
pylab.plot(ref[:,1],ref[:,2],marker='o',label="reference")
pylab.plot(data[:,1],data[:,2],label="test")
pylab.legend()
pylab.xlabel("strain")
pylab.ylabel("stress")
pylab.savefig("{}/stress_strain.png".format(outdir))


if (error > tolerance): raise Exception("Error in stress calculation")



#prof = ds.ray([0,0,0],[1,1,1],)
#df = prof.to_dataframe([("gas","x"),("gas","y"),("gas","z"),"disp_x"])
#
#x,y,z,u1 = [numpy.array(_x) for _x in zip(*sorted(zip(df["x"],df["y"],df["z"],df["disp_x"])))]
#
#if dim==2: u1_exact  =  - numpy.sin(numpy.pi*x) * numpy.sin(numpy.pi*y) / numpy.pi / numpy.pi / 2.0
#if dim==3: u1_exact  =  - numpy.sin(numpy.pi*x) * numpy.sin(numpy.pi*y) * numpy.sin(numpy.pi*z) / numpy.pi / numpy.pi / 3.0
#
#pylab.plot(x,u1,marker='o')
#pylab.plot(x,u1_exact)
#pylab.savefig("{}/u1.png".format(outdir))
#
#u1_err = sum((u1_exact - u1)**2) / sum(u1_exact**2)
#print("displacement error",u1_err)
#
#if u1_err > tolerance: raise(Exception("Error in u1"))
                               


