#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import glob

outdir = sys.argv[1]
ref = sys.argv[2]

tol = 1e-2

path = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 reference=ref,
                 start=[10, -5],
                 end  =[10, 5],
                 coord = "y",
                 vars=["momentumx","vorticity","pressure"],
                 tolerance=[tol, tol, tol],
                 abs_tolerance = 1e8, #ignore
                 generate_ref_data = False,
                 tight_layout=False,
)

exit(0)





