#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import glob

outdir = sys.argv[1]
reference = sys.argv[2]

path = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 reference=reference,
                 start=[0.0, 0.3125],
                 end  =[5.0, 0.3125],
                 coord = 'x',
                 vars=["eta", "momentumx","density","energy"],
                 tolerance=[0.01, 0.05,0.05,0.05],
                 generate_ref_data = False,
                 tight_layout=False,
)

testlib.warning("WARNING: currently using fairly generous tolerances.")
testlib.warning("         Once this is completely working, decrease acceptable")
testlib.warning("         error.")
exit(0)





