#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import glob

outdir = sys.argv[1]
reference = sys.argv[2]
path = sorted(glob.glob(f"{outdir}/*cell"))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 reference=reference,
                 vars=["Temp"],
                 tolerance=5E-3)
exit(0)





