#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import glob

outdir = sys.argv[1]
reference = sys.argv[2]

path = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 start=[-0.25, 0.2, 0],
                 end=[0.6, -0.6, 0],
                 vars=["alpha"],
                 tolerance=[0.05],
                 abs_tolerance=[0.05],
                 reference=reference,
                 generate_ref_data = False,
)
exit(0)





