#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import numpy, yt, pylab, os, pandas, sys, math

outdir = sys.argv[1]

generate_ref_data = False  # Change to True if you need to generate new reference data
tolerance = 0.05

path = "{}/00200cell/".format(outdir)
ds = yt.load(path)
dim = int(ds.domain_dimensions[0] > 1) + int(ds.domain_dimensions[1] > 1) + int(ds.domain_dimensions[2] > 1)

def integrate(x,y):
    ret = 0
    for i in range(len(x)-1): ret = ret + 0.5*(y[i+1]+y[i]) * (x[i+1]-x[i])
    return ret

testlib.validate(path="{}/00200cell/".format(outdir),
                 outdir=outdir,
                 start=[0,0,0],
                 end=[5,5,1],
                 vars=["Eta001","Eta002","Eta003","Eta004","Eta005","Eta006","Eta007","Eta008","Eta009","Eta010",],
                 tolerance=tolerance,
                 reference="reference/reference.csv",
                 filename_suffix="diag")
exit(0)

    


