#!/usr/bin/env python3
import sys, glob
sys.path.insert(0,"../../scripts")
import testlib

outdir = sys.argv[1]
checkfile = sys.argv[2]
datfile = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]
print(datfile)
start = [-4,0]
end   = [4,0]
coord = 'x'
vars = ["eta","velocity001","pressure"]

testlib.validate(path=datfile,
                 outdir=outdir,
                 start=start,
                 end=end,
                 vars=vars,
                 tolerance=1E-4,
                 generate_ref_data = False,
                 reference=checkfile,
                 coord=coord)
exit(0)





