#!/usr/bin/env python3
import numpy, yt, pylab, os, pandas, sys, math

outdir = sys.argv[1]

generate_ref_data = False  # Change to True if you need to generate new reference data
tolerance = 1E-7

path = "{}/04000cell/".format(outdir)
ds = yt.load(path)
dim = int(ds.domain_dimensions[0] > 1) + int(ds.domain_dimensions[1] > 1) + int(ds.domain_dimensions[2] > 1)

def integrate(x,y):
    ret = 0
    for i in range(len(x)-1): ret = ret + 0.5*(y[i+1]+y[i]) * (x[i+1]-x[i])
    return ret

if dim == 2:
    prof = ds.ray([0.0,0,0],[0.25,0,0],)

    df = prof.to_dataframe([("gas","x"),("gas","y"),"Eta"])

    if generate_ref_data:
        df.to_csv('reference/reference.csv')

    df_ref = pandas.read_csv('reference/reference.csv')

    class new:
        ret = [numpy.array(_x) for _x in zip(*sorted(zip(
            df["x"],df["y"],df["Eta"])))]
        x = ret[0]
        y = ret[1]
        eta = ret[2]
    class ref:
        ret = [numpy.array(_x) for _x in zip(*sorted(zip(
            df_ref["x"],df_ref["y"],df_ref["Eta"])))]
        x = ret[0]
        y = ret[1]
        eta = ret[2]

    pylab.clf()
    pylab.plot(ref.x,ref.eta,color='C0',label='reference')
    pylab.plot(new.x,new.eta,color='C1',label='new',linestyle='--')
    pylab.savefig("{}/etas.png".format(outdir))

    err = numpy.sqrt(integrate(ref.x, (numpy.interp(ref.x, new.x, new.eta) - ref.eta)**2))
    print("eta error",err)
    if err > tolerance: raise(Exception("Error in eta"))
    if math.isnan(err): raise(Exception("Errir is nan"))

if dim == 3:
    raise(Exception("Not implemented for 3D yet"))

exit(0)


    


