#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import glob

outdir = sys.argv[1]
#reference = sys.argv[2]

path = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 start=[1.5, 0],
                 end=[1.5, 1.0],
                 vars=["psi"],
                 tolerance=[0.01],
                 reference="reference/reference.dat", #reference,
                 coord='y',
                 generate_ref_data = False,
)
exit(0)





