#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib
import glob

outdir = sys.argv[1]

path = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 start=[-5,0,0],
                 end=[5,0,0],
                 vars=["eta001"],
                 tolerance=1E-6,
                 abs_tolerance = 10000, 
                 generate_ref_data = False,
)
exit(0)





