#!/usr/bin/env python3
"""Add source-comment documentation to an Alamo input schema JSON file."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Annotate alamo --parse-args JSON with comments scraped from source files."
    )
    parser.add_argument(
        "--schema",
        default="alamo-inputs.schema.json",
        type=Path,
        help="JSON schema generated by alamo --parse-args-output.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Annotated JSON output. Defaults to overwriting --schema.",
    )
    parser.add_argument(
        "--repo-root",
        default=repo_root,
        type=Path,
        help="Repository root used to resolve source paths from the schema.",
    )
    return parser.parse_args()


def split_cpp_line_comment(line: str) -> tuple[str, str]:
    quote = None
    escaped = False
    for index, char in enumerate(line):
        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
            continue

        if char in ['"', "'"]:
            quote = char
        elif char == "/" and index + 1 < len(line) and line[index + 1] == "/":
            return line[:index], line[index + 2 :].strip()

    return line, ""


def has_statement_semicolon(code: str) -> bool:
    quote = None
    escaped = False
    for char in code:
        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
            continue

        if char in ['"', "'"]:
            quote = char
        elif char == ";":
            return True

    return False


def preceding_comment_block(lines: list[str], line_index: int) -> list[str]:
    docs: list[str] = []
    for index in range(line_index - 1, -1, -1):
        match = re.fullmatch(r"\s*//(?!/)(?!\s*\[)\s*(.*?)\s*", lines[index])
        if not match:
            break
        text = match.group(1).strip()
        if text:
            docs.append(text)
    docs.reverse()
    return docs


def trailing_statement_comment(lines: list[str], line_index: int) -> str:
    for index in range(line_index, min(len(lines), line_index + 80)):
        code, comment = split_cpp_line_comment(lines[index])
        if has_statement_semicolon(code):
            return comment
    return ""


def clean_doc(parts: list[str]) -> str:
    return re.sub(r"\s+", " ", " ".join(part for part in parts if part).strip())


def comment_for_line(source_path: Path, line: int) -> str:
    if line <= 0:
        return ""
    lines = source_path.read_text(encoding="utf-8", errors="replace").splitlines()
    line_index = line - 1
    if line_index >= len(lines):
        return ""

    docs = preceding_comment_block(lines, line_index)
    trailing = trailing_statement_comment(lines, line_index)
    if trailing:
        docs.append(trailing)
    return clean_doc(docs)


def resolve_source_path(repo_root: Path, source_file: str) -> Path | None:
    path = Path(source_file)
    candidates = [path] if path.is_absolute() else [repo_root / path, Path.cwd() / path]
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    return None


def source_objects(value: Any):
    if isinstance(value, dict):
        source = value.get("source")
        if isinstance(source, dict) and source.get("file") and source.get("line"):
            yield value
        for child in value.values():
            yield from source_objects(child)
    elif isinstance(value, list):
        for child in value:
            yield from source_objects(child)


def deduplicate_constraint_docs(schema: dict[str, Any]) -> None:
    nodes_by_path: dict[str, dict[str, Any]] = {}
    constraints: list[dict[str, Any]] = []

    def collect(value: Any) -> None:
        if isinstance(value, dict):
            path = value.get("path")
            if isinstance(path, str):
                nodes_by_path[path] = value
            for constraint in value.get("constraints", []):
                if isinstance(constraint, dict):
                    constraints.append(constraint)
            for child in value.get("children", []):
                collect(child)
        elif isinstance(value, list):
            for child in value:
                collect(child)

    collect(schema.get("root", schema))
    for constraint in constraints:
        if constraint.get("kind") != "exactly" or not constraint.get("doc"):
            continue
        source = constraint.get("source")
        for member in constraint.get("members", []):
            node = nodes_by_path.get(member)
            if node is None or node.get("source") != source:
                continue
            node.pop("doc", None)
            node.pop("description", None)


def annotate_schema(schema: dict[str, Any], repo_root: Path) -> tuple[int, int, int]:
    annotated = 0
    missing_doc = 0
    missing_source = 0
    cache: dict[tuple[str, int], str] = {}
    resolved: dict[str, Path | None] = {}

    for obj in source_objects(schema):
        source = obj["source"]
        source_file = str(source["file"])
        try:
            line = int(source["line"])
        except (TypeError, ValueError):
            missing_source += 1
            continue

        if source_file not in resolved:
            resolved[source_file] = resolve_source_path(repo_root, source_file)
        source_path = resolved[source_file]
        if source_path is None:
            missing_source += 1
            continue

        key = (str(source_path), line)
        if key not in cache:
            cache[key] = comment_for_line(source_path, line)
        doc = cache[key]
        if not doc:
            missing_doc += 1
            continue

        obj["doc"] = doc
        obj["description"] = doc
        annotated += 1

    deduplicate_constraint_docs(schema)
    return annotated, missing_doc, missing_source


def main() -> None:
    args = parse_args()
    with args.schema.open("r", encoding="utf-8") as schema_file:
        schema = json.load(schema_file)

    annotated, missing_doc, missing_source = annotate_schema(
        schema, args.repo_root.resolve()
    )

    output = args.output or args.schema
    output.write_text(json.dumps(schema, indent=2) + "\n", encoding="utf-8")
    print(
        f"Wrote {output} "
        f"({annotated} annotated, {missing_doc} without comments, "
        f"{missing_source} unresolved sources)"
    )


if __name__ == "__main__":
    main()
