#!/usr/bin/env python3
"""Check source ParmParse input calls against generated parse-args schemas."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable


INPUT_METHODS = {
    "query",
    "query_required",
    "query_default",
    "query_validate",
    "query_switch",
    "query_if",
    "query_file",
    "queryunit",
    "queryarr",
    "queryarr_required",
    "queryarr_default",
    "queryclass",
    "query_enumerate",
    "queryarr_enumerate",
    "queryclass_enumerate",
    "query_customname",
    "query_exactly",
    "select",
    "select_default",
    "select_enumerate",
}

SOURCE_SUFFIXES = {".H", ".HH", ".HPP", ".h", ".hh", ".hpp", ".cpp", ".cc", ".cxx"}
DEFAULT_EXCLUDED_SOURCE_FILES = {
    "src/IO/ParmParse.H",
    "src/IO/InputScraper.H",
    "src/IO/InputScraper.cpp",
}

METHOD_PATTERN = "|".join(sorted(map(re.escape, INPUT_METHODS), key=len, reverse=True))
CALL_RE = re.compile(
    rf"""
    (?:
      \bpp_(?P<macro_method>{METHOD_PATTERN})\b\s*(?:<[^;()]*>\s*)?\(
      |
      \b(?P<object>[A-Za-z_]\w*)\s*(?:\.|->)\s*
      (?P<member_method>{METHOD_PATTERN})\b\s*(?:<[^;()]*>\s*)?\(
    )
    """,
    re.VERBOSE | re.DOTALL,
)
IGNORE_TRAVERSAL_RE = re.compile(
    r"\bIO\s*::\s*ParmParse\s*::\s*IgnoreInTraversalMode\s*\("
)


@dataclass(frozen=True)
class CallSite:
    file: str
    line: int
    method: str
    name: str | None
    spelling: str
    code: str

    @property
    def key(self) -> tuple[str, int]:
        return (self.file, self.line)


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description=(
            "Scan source files for ParmParse input call sites and compare them "
            "with the source locations emitted by --parse-args JSON schemas."
        )
    )
    parser.add_argument(
        "--repo-root",
        default=repo_root,
        type=Path,
        help="Repository root to scan.",
    )
    parser.add_argument(
        "--schema-dir",
        default=repo_root / "docs/source/_static/input-schemas",
        type=Path,
        help="Directory containing *.schema.json files generated by parse-args.",
    )
    parser.add_argument(
        "--schema",
        action="append",
        default=[],
        type=Path,
        help="Schema to include in coverage. May be repeated; defaults to every schema in --schema-dir.",
    )
    parser.add_argument(
        "--source-dir",
        default=repo_root / "src",
        type=Path,
        help="Source directory or individual source file to scan.",
    )
    parser.add_argument(
        "--report",
        type=Path,
        help="Optional JSON report path.",
    )
    parser.add_argument(
        "--fail-on-missing",
        action="store_true",
        help="Exit nonzero if uncaptured call sites are found.",
    )
    parser.add_argument(
        "--max-list",
        default=40,
        type=int,
        help="Maximum uncaptured call sites to print to stdout.",
    )
    parser.add_argument(
        "--exclude",
        action="append",
        default=[],
        help="Repo-relative source file to exclude from scanning. May be repeated.",
    )
    return parser.parse_args()


def normalize_repo_path(repo_root: Path, path: str | Path) -> str:
    path = Path(path)
    if not path.is_absolute():
        path = repo_root / path
    try:
        return path.resolve().relative_to(repo_root.resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def mask_comments(text: str) -> str:
    chars = list(text)
    i = 0
    quote: str | None = None
    escaped = False

    while i < len(chars):
        char = chars[i]

        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
            i += 1
            continue

        if char in {'"', "'"}:
            quote = char
            i += 1
            continue

        if char == "/" and i + 1 < len(chars) and chars[i + 1] == "/":
            chars[i] = " "
            chars[i + 1] = " "
            i += 2
            while i < len(chars) and chars[i] != "\n":
                chars[i] = " "
                i += 1
            continue

        if char == "/" and i + 1 < len(chars) and chars[i + 1] == "*":
            chars[i] = " "
            chars[i + 1] = " "
            i += 2
            while i + 1 < len(chars):
                if chars[i] == "*" and chars[i + 1] == "/":
                    chars[i] = " "
                    chars[i + 1] = " "
                    i += 2
                    break
                if chars[i] != "\n":
                    chars[i] = " "
                i += 1
            continue

        i += 1

    return "".join(chars)


def string_ranges(text: str) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    i = 0
    quote: str | None = None
    start = 0
    escaped = False

    while i < len(text):
        char = text[i]
        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                ranges.append((start, i + 1))
                quote = None
            i += 1
            continue

        if char in {'"', "'"}:
            quote = char
            start = i
        i += 1

    return ranges


def offset_in_ranges(offset: int, ranges: list[tuple[int, int]]) -> bool:
    return any(start <= offset < end for start, end in ranges)


def matching_parenthesis(text: str, opening: int) -> int | None:
    depth = 0
    quote: str | None = None
    escaped = False

    for index in range(opening, len(text)):
        char = text[index]

        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
            continue

        if char in {'"', "'"}:
            quote = char
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return index

    return None


def split_cpp_arguments(arguments: str) -> list[str]:
    ret: list[str] = []
    start = 0
    depths = {"(": 0, "[": 0, "{": 0, "<": 0}
    closing = {")": "(", "]": "[", "}": "{", ">": "<"}
    quote: str | None = None
    escaped = False

    for index, char in enumerate(arguments):
        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
            continue

        if char in {'"', "'"}:
            quote = char
        elif char in depths:
            depths[char] += 1
        elif char in closing:
            opener = closing[char]
            depths[opener] = max(0, depths[opener] - 1)
        elif char == "," and not any(depths.values()):
            ret.append(arguments[start:index].strip())
            start = index + 1

    tail = arguments[start:].strip()
    if tail:
        ret.append(tail)
    return ret


def first_string_argument(arguments: list[str]) -> str | None:
    if not arguments:
        return None
    match = re.fullmatch(r'\s*"([^"]+)"\s*', arguments[0], re.DOTALL)
    return match.group(1) if match else None


def source_files(repo_root: Path, source_dir: Path, excluded: set[str]) -> Iterable[Path]:
    candidates = [source_dir] if source_dir.is_file() else source_dir.rglob("*")
    for path in sorted(candidates):
        if (
            path.is_file()
            and path.suffix in SOURCE_SUFFIXES
            and normalize_repo_path(repo_root, path) not in excluded
        ):
            yield path


def line_for_offset(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def is_preprocessor_line(lines: list[str], line: int) -> bool:
    if line < 1 or line > len(lines):
        return False
    return lines[line - 1].lstrip().startswith("#")


def call_code(lines: list[str], start_line: int, end_line: int) -> str:
    snippet = " ".join(line.strip() for line in lines[start_line - 1 : end_line])
    return re.sub(r"\s+", " ", snippet).strip()


def scan_source_file(repo_root: Path, path: Path) -> list[CallSite]:
    text = path.read_text(encoding="utf-8", errors="replace")
    masked = mask_comments(text)
    string_spans = string_ranges(masked)
    lines = text.splitlines()
    relpath = normalize_repo_path(repo_root, path)
    calls: list[CallSite] = []

    for match in CALL_RE.finditer(masked):
        if offset_in_ranges(match.start(), string_spans):
            continue
        start_line = line_for_offset(masked, match.start())
        if is_preprocessor_line(lines, start_line):
            continue

        opening = match.end() - 1
        closing = matching_parenthesis(masked, opening)
        if closing is None:
            continue

        method = match.group("macro_method") or match.group("member_method")
        arguments = split_cpp_arguments(masked[opening + 1 : closing])
        end_line = line_for_offset(masked, closing)
        calls.append(
            CallSite(
                file=relpath,
                line=start_line,
                method=method,
                name=first_string_argument(arguments),
                spelling="macro" if match.group("macro_method") else "member",
                code=call_code(lines, start_line, end_line),
            )
        )

    return calls


def source_objects(value: Any) -> Iterable[dict[str, Any]]:
    if isinstance(value, dict):
        source = value.get("source")
        if isinstance(source, dict) and source.get("file") and source.get("line"):
            yield value
        for child in value.values():
            yield from source_objects(child)
    elif isinstance(value, list):
        for child in value:
            yield from source_objects(child)


def schema_paths(value: Any) -> Iterable[str]:
    if isinstance(value, dict):
        path = value.get("path")
        if isinstance(path, str) and path:
            yield path
        for child in value.values():
            yield from schema_paths(child)
    elif isinstance(value, list):
        for child in value:
            yield from schema_paths(child)


def traversal_ignores(value: Any, repo_root: Path) -> list[dict[str, str | int]]:
    if not isinstance(value, dict):
        return []

    ignores: list[dict[str, str | int]] = []
    for item in value.get("traversal_ignored", []):
        if not isinstance(item, dict) or not isinstance(item.get("source"), dict):
            continue
        source = item["source"]
        source_file = source.get("file")
        source_line = source.get("line")
        if not isinstance(source_file, str):
            continue
        try:
            line = int(source_line)
        except (TypeError, ValueError):
            continue
        ignores.append(
            {
                "file": normalize_repo_path(repo_root, source_file),
                "line": line,
                "note": str(item.get("note", "")),
            }
        )
    return ignores


def load_schema_coverage(
    repo_root: Path, schema_dir: Path, requested_schemas: list[Path]
) -> tuple[set[tuple[str, int]], set[str], list[dict[str, str | int]], list[str]]:
    captured_locations: set[tuple[str, int]] = set()
    captured_paths: set[str] = set()
    ignored: list[dict[str, str | int]] = []
    schemas = (
        sorted(requested_schemas)
        if requested_schemas
        else sorted(schema_dir.glob("*.schema.json"))
    )

    for schema_path in schemas:
        with schema_path.open("r", encoding="utf-8") as schema_file:
            schema = json.load(schema_file)

        captured_paths.update(schema_paths(schema))
        ignored.extend(traversal_ignores(schema, repo_root))
        for obj in source_objects(schema):
            source = obj["source"]
            try:
                line = int(source["line"])
            except (TypeError, ValueError):
                continue
            captured_locations.add((normalize_repo_path(repo_root, str(source["file"])), line))

    return captured_locations, captured_paths, ignored, [path.as_posix() for path in schemas]


def candidate_names(call: CallSite) -> set[str]:
    if not call.name:
        return set()
    names = {call.name}
    if call.method in {"select", "select_default"}:
        names.add(f"{call.name}.type")
    return names


def build_report(
    repo_root: Path,
    source_dir: Path,
    schema_dir: Path,
    requested_schemas: list[Path],
    excluded: set[str],
) -> dict[str, Any]:
    captured_locations, captured_paths, traversal_ignored, schemas = load_schema_coverage(
        repo_root, schema_dir, requested_schemas
    )
    ignored_source_files = {str(item["file"]) for item in traversal_ignored}
    source_calls = [
        call
        for path in source_files(repo_root, source_dir, excluded)
        for call in scan_source_file(repo_root, path)
    ]

    captured: list[CallSite] = []
    covered_by_name: list[CallSite] = []
    ignored: list[CallSite] = []
    missing: list[CallSite] = []

    for call in source_calls:
        if call.file in ignored_source_files:
            ignored.append(call)
        elif call.key in captured_locations:
            captured.append(call)
        elif candidate_names(call) & captured_paths:
            covered_by_name.append(call)
        else:
            missing.append(call)

    method_counts: dict[str, int] = {}
    missing_method_counts: dict[str, int] = {}
    for call in source_calls:
        method_counts[call.method] = method_counts.get(call.method, 0) + 1
    for call in missing:
        missing_method_counts[call.method] = missing_method_counts.get(call.method, 0) + 1

    return {
        "schema_dir": normalize_repo_path(repo_root, schema_dir),
        "schemas": schemas,
        "source_dir": normalize_repo_path(repo_root, source_dir),
        "excluded_source_files": sorted(excluded),
        "total_source_call_sites": len(source_calls),
        "captured_by_source_location": len(captured),
        "covered_by_schema_name": len(covered_by_name),
        "ignored_by_traversal_opt_out": len(ignored),
        "ignored_source_files": sorted(ignored_source_files),
        "traversal_ignored": traversal_ignored,
        "missing": len(missing),
        "method_counts": dict(sorted(method_counts.items())),
        "missing_method_counts": dict(sorted(missing_method_counts.items())),
        "missing_call_sites": [asdict(call) for call in missing],
        "ignored_call_sites": [asdict(call) for call in ignored],
        "covered_by_name_call_sites": [asdict(call) for call in covered_by_name],
    }


def print_summary(report: dict[str, Any], max_list: int) -> None:
    print(
        "Input scrape coverage: "
        f"{report['captured_by_source_location']} captured by source location, "
        f"{report['covered_by_schema_name']} covered by schema name, "
        f"{report['ignored_by_traversal_opt_out']} intentionally ignored, "
        f"{report['missing']} missing "
        f"out of {report['total_source_call_sites']} source call sites."
    )

    missing = report["missing_call_sites"]
    if not missing:
        return

    print("Uncaptured ParmParse input call sites:")
    for call in missing[:max_list]:
        name = f" {call['name']!r}" if call["name"] else ""
        print(f"  {call['file']}:{call['line']} {call['method']}{name}")
        print(f"    {call['code']}")
    if len(missing) > max_list:
        print(f"  ... {len(missing) - max_list} more")


def main() -> int:
    args = parse_args()
    repo_root = args.repo_root.resolve()
    source_dir = args.source_dir
    schema_dir = args.schema_dir

    if not source_dir.is_absolute():
        source_dir = repo_root / source_dir
    if not schema_dir.is_absolute():
        schema_dir = repo_root / schema_dir
    requested_schemas = [
        schema if schema.is_absolute() else repo_root / schema
        for schema in args.schema
    ]

    excluded = set(DEFAULT_EXCLUDED_SOURCE_FILES)
    excluded.update(normalize_repo_path(repo_root, item) for item in args.exclude)

    report = build_report(
        repo_root,
        source_dir.resolve(),
        schema_dir.resolve(),
        requested_schemas,
        excluded,
    )
    if args.report:
        report_path = args.report if args.report.is_absolute() else repo_root / args.report
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    print_summary(report, args.max_list)

    if args.fail_on_missing and report["missing"]:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
