#!/usr/bin/env python3
"""Generate a standalone HTML assembler for Alamo input files."""

from __future__ import annotations

import argparse
import json
from html import escape
from pathlib import Path


TEMPLATE_PATH = Path(__file__).with_name("input_builder_template.html")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Embed an Alamo input schema JSON file into a static HTML input builder."
    )
    parser.add_argument(
        "--schema",
        default="alamo-inputs.schema.json",
        type=Path,
        help="JSON schema generated by alamo --parse-args-output.",
    )
    parser.add_argument(
        "--output",
        default="input-builder.html",
        type=Path,
        help="Standalone HTML file to write.",
    )
    parser.add_argument(
        "--title",
        default="Alamo Input Builder",
        help="Title shown in the generated page.",
    )
    return parser.parse_args()


def make_script_safe_json(data: object) -> str:
    text = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    return text.replace("&", "\\u0026").replace("<", "\\u003c").replace(">", "\\u003e")


def render_html(schema: object, schema_path: Path, title: str) -> str:
    html = TEMPLATE_PATH.read_text(encoding="utf-8")
    return (
        html.replace("__TITLE__", escape(title))
        .replace("__SCHEMA_SOURCE__", escape(str(schema_path)))
        .replace("__SCHEMA_JSON__", make_script_safe_json(schema))
    )


def main() -> None:
    args = parse_args()
    with args.schema.open("r", encoding="utf-8") as schema_file:
        schema = json.load(schema_file)

    args.output.write_text(
        render_html(schema, args.schema, args.title),
        encoding="utf-8",
    )
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
