#!/usr/bin/env python3
import sys
sys.path.insert(0,"../../scripts")
import testlib

outdir = sys.argv[1]

testlib.validate(path="{}/01000cell/".format(outdir),
                 outdir=outdir,
                 start=[-0.5,0,0],
                 end=[0.5,0,1],
                 vars=["alpha"],
                 tolerance=1E-6,
                 generate_ref_data = True)

exit(0)





