#!/usr/bin/env python3
import sys,glob
sys.path.insert(0,"../../scripts")
import testlib

outdir = sys.argv[1]
reference = sys.argv[2]

path = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

testlib.validate(path=path,
                 outdir=outdir,
                 start=[0,0,0],
                 end=[1,1,0],
                 vars=["temperature", "pressure", "mass_fraction001", "mass_fraction006"],
                 reference=reference,
                 tolerance=[0.05,0.05,0.05,0.05],
                 abs_tolerance=1E100, #ignore absolute tolerance
                 #generate_ref_data = True,
                 tight_layout=False)
exit(0)





