name: C/C++ CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure  --build-amrex --dim=2 --no-diff
    - name: make
      run: make
    - name: test
      run: ./bin/test-2d-g++
