on:
  push:
    branches-ignore: []

jobs:
  cuda80:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: installing preliminaries
      run: bash .github/workflows/dependencies-ubuntu-24.04.sh
    - name: configure (3d)
      run: ./configure --cuda --dim=2 
    - name: make
      run: make
