name: Install

on:
  workflow_call:
  push:
    branches: ["development", "master", "candidate", "candidate-install"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: install-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: running the install script
      run: bash .github/workflows/dependencies-ubuntu-22.04.sh
    - name: build and test
      run: bash .github/workflows/build-and-test.sh --comp=g++
  install-ubuntu-24-04:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: running the install script
      run: bash .github/workflows/dependencies-ubuntu-24.04.sh
    - name: build and test
      run: bash .github/workflows/build-and-test.sh
    - name: python
      run: bash .github/workflows/python.sh
  install-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: running the install script
      run: bash .github/workflows/install-macos.sh
