name: Memory Leak Check

on:
  push:
    branches-ignore: ["candidate-install"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-coverage:
    name: Compile in debug and run valgrind
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: installing preliminaries
      run: bash .github/workflows/dependencies.sh
    - name: configure (2d)
      continue-on-error: true
      run: ./configure --dim=2 --debug --memcheck
    - name: make (2d)
      run: make
    - name: regression tests with memory checking (2d)
      run: ./scripts/runtests --debug --serial --dim=2 --memcheck
