#!/usr/bin/env python3
import sys, glob
sys.path.insert(0,"../../scripts")
import testlib

outdir = sys.argv[1]
checkfile = sys.argv[2]
datfile = sorted(glob.glob("{}/*cell/".format(outdir)))[-1]

if "-x" in checkfile:
    start = [-3,0]
    end   = [4,0]
    vars = ["eta","density","velocityx","pressure"]
    coord = 'x'
elif "-y" in checkfile:
    start = [0,-3]
    end   = [0,4]
    vars = ["eta","density","velocityx","pressure"]
    coord = 'y'

testlib.validate(path=datfile,
                 outdir=outdir,
                 start=start,
                 end=end,
                 vars=vars,
                 tolerance=1E-4,
                 generate_ref_data = False,
                 reference=checkfile,
                 coord=coord)
exit(0)





